name: ghcr.io workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Docker environment
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Docker image
        uses: docker/build-push-action@v2.0.1
        with:
          tags: ghcr.io/pere3/asynchttp-hello:latest
      - name: Push Docker image
        run: docker push ghcr.io/pere3/asynchttp-hello:latest

